config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_closure_tree

  belongs_to :story, counter_cache: true
  belongs_to :account, counter_cache: true, optional: true
  has_many :votes, as: :voteable

  scope :local, -> { where(uri: nil) }
  scope :remote, -> { where.not(uri: nil) }

  def cache_depth
    update_attributes(depth_cached: depth)
  end

  def cache_body
    update_attributes(
      body_html: BodyParser.new(body).call
    )
  end

  def object_type
    :note
  end

  def self.find_local(id)
    find_by(id: id, domain: nil)
  end
end

app/controllers/accounts/comments_controller.rb
class Accounts::CommentsController < ApplicationController
  layout 'application'

  before_action :set_account_upvoted_comment_ids

  def hot
    @account = find_account
    @page_title = "Hot comments by #{@account.decorate}"
    comments = CommentsQuery.new.hot
    comments = CommentsQuery.new(comments).by_account(@account)

    @comments = comments.page(params[:page])

    render :index
  end

  def recent
    @account = find_account
    @page_title = "Recent comments by #{@account.decorate}"
    comments = CommentsQuery.new.recent
    comments = CommentsQuery.new(comments).by_account(@account)

    @comments = comments.page(params[:page])

    render :index
  end

  private

  def find_account
    Account.local.find_by!(username: params[:username]).decorate
  end
end

app/controllers/api/ujs/comments_controller.rb
class Api::Ujs::CommentsController < Api::Ujs::BaseController
  before_action :set_account_upvoted_comment_ids

  def new
    story = Story.find(params[:story_id])

    @comment = Comments::Create.new
    @comment.story_id = params[:story_id]
    @comment.parent_id = params[:parent_id]

    render 'comments/new', layout: false
  end

  def create
    commentable = find_commentable
    authorize commentable, :comment?

    outcome = Comments::Create.run(
      parent_id: params.fetch(:comment)[:parent_id].presence,
      story_id: params.fetch(:comment)[:story_id],
      body: params.fetch(:comment)[:body],
      account: current_user.account,
      local: true
    )

    if outcome.valid?
      set_account_upvoted_comment_ids
      render 'comments/_comment', layout: false, locals: { comment: outcome.result }, status: :created
    else
      @comment = outcome
      render 'comments/new', layout: false, status: :bad_request
    end
  end

  def edit
    comment = find_comment
    authorize comment

    @comment = Comments::Update.new(
      comment: comment,
      body: comment.body
    )

    render 'comments/edit', layout: false
  end

  def update
    comment = find_comment
    authorize comment

    outcome = Comments::Update.run(
      comment: comment,
      body: params.fetch(:comment)[:body],
      account: current_account
    )

    if outcome.valid?
      render 'comments/_comment', layout: false, locals: { comment: outcome.result }, status: :created
    else
      @comment = outcome
      render 'comments/edit', layout: false, status: :bad_request
    end
  end

  def toggle_vote
    user_needed
    comment = find_comment
    authorize comment

    outcome = Comments::ToggleVote.run(comment: comment, account: current_user.account)
    set_account_upvoted_comment_ids

    render 'comments/_comment', layout: false, locals: { comment: outcome.result.voteable }
  end

  private

  def find_comment
    Comment.find(params[:id])
  end

  def find_commentable
    if params[:parent_id].present?
      Comment.find(params[:comment][:parent_id])
    else
      Story.find(params[:comment][:story_id])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout 'application'

  before_action :set_account_upvoted_comment_ids

  def index
    comments = CommentsQuery.new.hot
    comments = CommentsQuery.new(comments).with_story
    @comments = comments.page(params[:page])
  end

  def recent
    comments = CommentsQuery.new.recent
    comments = CommentsQuery.new(comments).with_story
    @comments = comments.page(params[:page])
    render :index
  end

  def show
    set_account_upvoted_story_ids

    comment = find_comment
    @comment = comment.removed? ? RemovedCommentNull.new(comment) : comment
    @children = @comment.children.includes(:account).hash_tree

    respond_to do |format|
      format.html
      format.json do
        render json: ActivityPub::CommentSerializer.new(@comment),
               with_context: true,
               content_type: 'application/activity+json'
      end
    end
  end

  private

  def find_comment
    Comment.find(params[:id])
  end
end

app/views/comments/_comment.html.slim
- presenter = CommentPresenter.new(comment,
                                   local_assigns.merge(upvoted_ids: @account_upvoted_comment_ids,
                                                       current_user: current_user))
- account = presenter.account&.decorate

li.comment(
  data-controller="comment"
  data-id=comment.id
  data-parent-id=comment.parent_id
  class=presenter.root_classes
  data-voted=presenter.upvoted?.to_s
)
  .comment-inner
    ul.list-inline.comment-meta(data-action="click->comment#toogleClosed")
      li.list-inline-item.comment-avatar
        = image_tag account.avatar_url(:size_60), class: 'avatar avatar-xs'

      li.list-inline-item.comment-author
        = presenter.linked_account_username

      li.list-inline-item
        = link_to comment do
          span(data-controller="time-ago" data-datetime=comment.created_at.iso8601)
            = comment.created_at

      - if presenter.show_story?
        li.list-inline-item
          | •
        li.list-inline-item
          | on: #{link_to comment.story.title, comment.story}

    / Comment body
    .comment-body(data-target="comment.bodyContainer")
      div == presenter.comment.body_html

    / Bottom meta
    ul.list-inline.comment-actions(data-target="comment.actionsContainer")
      li.list-inline-item.comment-actions-vote-btn
        - if presenter.can_vote?
          a.comment-vote-btn(
            data-action="click->comment#toggleVote"
            data-target="comment.voteBtn"
            data-action-path=toggle_vote_api_ujs_comment_path(comment)
          )
            = presenter.vote_button_label

        - else
          .comment-vote-btn = presenter.vote_button_label

      li.list-inline-item
          | /

      li.list-inline-item.comment-actions-replies
        | #{comment.children_count} replies

      li.list-inline-item
        | •

      li.list-inline-item
        = link_to 'link', comment

      - if presenter.show_parent_link?
        li.list-inline-item
          = link_to 'parent', comment_path(id: comment.parent_id)

      li.list-inline-item
        | •

      - if presenter.show_reply_link?
        li.list-inline-item
          a.comment-reply-btn(data-action="comment#showReply") reply

      - if presenter.show_edit?
        li.list-inline-item
          a.comment-edit-btn(data-action="comment#showEdit") edit

  / Edit form
  .comment-edit-container(
    data-target="comment.editContainer"
    data-action-path=edit_api_ujs_comment_path(comment)
  )

  / Reply form
  .comment-reply-container(
    data-target="comment.replyContainer"
    data-action-path=new_api_ujs_comment_path(story_id: comment.story_id, parent_id: comment.id)
  )

  / Child comments
  ul.comment-children
    - if presenter.show_children?
      - children.each do |comment, children|
        = render 'comments/comment', comment: comment, children: children, show_children: true

app/views/comments/_form.html.slim
- body_placeholder = user_signed_in? ? 'Write your comment here...' : 'You need to be signed-in to write comments.'
- url = comment.is_a?(Comments::Create) ? api_ujs_comments_path : api_ujs_comment_path(comment.comment)
- controller_mode = comment.is_a?(Comments::Create) ? 'create' : 'update'

= simple_form_for comment, as: :comment,
                           url: url,
                           remote: true,
                           wrapper: :spectre_vertical_form,
                           html: { data: { controller: 'new-comment', 'parent-id': @comment.try(:parent_id), mode: controller_mode } } do |f|

  - if comment.is_a?(Comments::Create)
    = f.input :story_id, as: :hidden
    = f.input :parent_id, as: :hidden

  .form-group
    = f.input :body, as: :text,
                     placeholder: body_placeholder,
                     label: false,
                     disabled: !user_signed_in?,
                     input_html: { rows: 3, data: { target: 'new-comment.body' } }

  .form-group
    = f.submit class: 'btn btn-primary btn-sm', disabled: !user_signed_in?

    - if comment.is_a?(Comments::Update)
      button.btn.btn-link.btn-sm.ml-1(
        data-action="click->comment#cancelEdit"
      ) Cancel

app/views/comments/_list.html.slim
- show_parent_link = defined?(show_parent_link) && show_parent_link ? show_parent_link : false
- show_story = defined?(show_story) && show_story ? show_story : false
- show_children = defined?(show_children) && show_children ? show_children : false
- show_reply_link = local_assigns.has_key?(:show_reply_link) ? show_reply_link : true

- if comments.any?
  ul.comment-children(style="padding: 0 1rem")
    - @comments.each do |comment|
      = render 'comments/comment', comment: comment,
                                   show_story: show_story,
                                   show_children: show_children,
                                   show_reply_link: show_reply_link

- else
  .empty(data-target="first-comment.empty")
    .empty-icon
      | &times;
    p.empty-title.h5 No comments to show
    p.empty-subtitle Maybe try changing search criteria?

app/views/comments/edit.html.slim
= render 'comments/form', comment: @comment

app/views/comments/index.html.slim
.columns
  .column.col-12
    .box
      .box-nav
        ul.tab
          li.tab-item
            = active_link_to 'Hot', comments_path, active: :exclusive
          li.tab-item
            = active_link_to 'Recent', recent_comments_path

      .box-body
        = render 'comments/list', comments: @comments,
                                  show_reply_link: false,
                                  show_story: true

    = paginate @comments, theme: :mini_box

app/views/comments/new.html.slim
= render 'comments/form', comment: @comment

app/views/comments/show.html.slim
- set_meta_tags @comment.decorate

.columns
  .column.col-12
    .stories-list
      ul.list-unstyled
        = render @comment.story

    .box(data-controller="comments-tree")
      .box-body.p-4
        .bg-gray.p-3.br-3
          p.mb-2 That's only a part of entire conversation.
          p.m-0
            a.btn.btn-sm.btn-gray(href=@comment.story.decorate.path)
              | See all the comments

            - if @comment.parent_id.present?
              a.btn.btn-sm.btn-gray.ml-2(href=comment_path(@comment.parent_id))
                | See parent comment

        ul.comment-children
          = render 'comments/comment', comment: @comment,
                                       children: @children,
                                       show_children: true