config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  EVENT_KEYS = %w[comment_reply story_reply new_follower].freeze

  belongs_to :author, polymorphic: true
  belongs_to :recipient, polymorphic: true
  belongs_to :notifable, polymorphic: true, optional: true
  belongs_to :context, polymorphic: true, optional: true

  scope :seen, ->{ where(seen: true) }
  scope :not_seen, ->{ where(seen: false) }

  validates :event_key, inclusion: { in: EVENT_KEYS }
end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < Api::V1Controller
  before_action :authenticate_user!

  def unread_count
    notifications = current_account.notifications_as_recipient.not_seen
    render json: { count: notifications.count }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  after_action :mark_all_as_read, only: %i[index unread]

  def index
    @notifications = find_notifications.page(params[:page])
  end

  def unread
    @notifications = find_notifications.not_seen.limit(100)
    render :index
  end

  private

  def find_notifications
    @find_notifications ||= current_account.notifications_as_recipient
                                           .includes(:author, :notifable, :context)
                                           .order(id: :desc)
  end

  def mark_all_as_read
    Notifications::MarkAllAsRead.run!(account: current_account)
  end
end

app/views/notifications/index.html.slim
.columns
  .column.col-12
    .box.tag-head
      .box-body
        h2.m-0 Notifications

    .box
      .box-nav
        ul.tab
          li.tab-item
            = active_link_to 'All', notifications_path, active: :exclusive
          li.tab-item
            = active_link_to 'Unread', unread_notifications_path

      - @notifications.each do |n, notification = NotificationPresenter.new(n)|
        .tile.notifications-item(class=('bg-secondary' if !notification.seen?))
          .tile-icon
            a(href=notification.author.decorate.path)
              img.avatar.avatar-lg(src=notification.author.avatar_url(:size_60))

          .tile-content
            p
              = notification.sentence

            p.text-gray.notifications-item-when(data-controller="time-ago" data-datetime=notification.created_at.iso8601)
              = notification.created_at

      - if @notifications.empty?
        .empty.empty-transparent
          .empty-icon
            | &times;
          p.empty-title.h5 Nothing to show

    - if @notifications.try(:total_pages)
      = paginate @notifications, theme: :mini_box