config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/views/shared/_flash.html.slim
.flashes(data-controller="flashes")
  - flash.each do |severity, value|
    .flashes-item(
      data-severity=severity
      data-value=value
      data-target="flashes.item"
    )

app/views/shared/_footer.html.slim
footer.text-center
  p powered by <a href="https://gitlab.com/mbajur/prismo"><span>△</span> Prismo</a> #{Prismo::Version}

app/views/shared/_head.html.slim
meta(name="current-account-id" content=current_account&.id)
link(id="favicon" rel="icon" href="/favicon.png" type="image/png" sizes="16x16" data-controller="favicon")

app/views/shared/_navbar.html.slim
header.navbar-main
  .container(style="width: 990px;")
    .navbar
      section.navbar-section
        = link_to Setting.site_title, root_path, class: 'navbar-brand'
        = active_link_to 'Stories', root_path, class: 'btn btn-link', active: { controller: :stories }
        = active_link_to 'Comments', comments_path, class: 'btn btn-link'

      section.navbar-section
        = active_link_to '+ Add story', new_story_path, class: 'btn btn-link'

        - if user_signed_in?
          a.btn.btn-link.navbar-main-notifications#notifications-indicator(
            href=notifications_path
            data-controller="notifications-indicator"
            data-turbolinks-permanent=true
            data-notifications-indicator-all-path=notifications_path
            data-notifications-indicator-unread-path=unread_notifications_path
            title="Notifications"
          )
            i.icon.icon-message

          .dropdown.dropdown-right.navbar-main-profile
            a.btn.btn-link.dropdown-toggle(href="javascript:void(0);")
              = image_tag current_account.avatar_url(:size_60), class: 'avatar'

            ul.menu
              li.menu-item
                .tile.tile-centered
                  .tile-icon
                    = image_tag current_account.avatar_url(:size_60), class: 'avatar'
                  .tile-content = current_account

              li.divider
              li.menu-item
                = link_to 'My Profile', current_account.path
              li.menu-item
                = link_to 'Settings', settings_profile_path

              - if current_user.is_admin?
                li.menu-item
                  = link_to 'Admin', edit_admin_settings_path

              li.divider
              li.menu-item
                = link_to 'Sign-out', destroy_user_session_path, data: { method: "delete" }
        - else
          = link_to 'Join us', new_user_session_path, class: 'btn btn-link'

app/views/shared/_popular_tags.html.slim
- tags = TagsQuery.new.popular.first(10).map(&:decorate)

.box.mb-2.popular-tags
  .box-body
    ul.list-inline
      - tags.each do |tag|
        li.list-inline-item
          a(href=tag.path) ##{tag.name}