config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  resources :stories, path: :posts do
    get :recent, on: :collection
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      resources :stories, only: [] do
        post :toggle_vote, on: :member
        post :scrap, on: :member
      end

      resources :comments, only: [:new, :create, :edit, :update] do
        post :toggle_vote, on: :member
      end
    end

    namespace :v1 do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
  end
end

app/models/story.rb
class Story < ApplicationRecord
  Gutentag::ActiveRecord.call self

  attr_accessor :tag_list

  belongs_to :account, counter_cache: true
  has_many :comments, dependent: :destroy
  belongs_to :url_meta, optional: true
  has_many :votes, as: :voteable
  belongs_to :group, optional: true

  validates :url, allow_blank: true, uniqueness: true

  delegate :thumb, :thumb_url, :thumb_data?,
           to: :url_meta,
           allow_nil: true

  scope :local, ->{ where(domain: nil) }

  def article?
    url.empty?
  end

  def object_type
    article? ? :article : :page
  end

  def self.find_local(id)
    find_by(id: id, domain: nil)
  end
end

app/controllers/accounts/stories_controller.rb
class Accounts::StoriesController < ApplicationController
  layout 'application'

  before_action :set_account_upvoted_story_ids

  def hot
    @account = find_account
    set_meta_tags @account.decorate
                          .to_meta_tags
                          .merge(title: "Hot stories by #{@account.decorate}")

    stories = StoriesQuery.new.hot
    stories = StoriesQuery.new(stories).for_account(@account)

    @stories = stories.page(params[:page])

    respond_to do |format|
      format.html { render :index }
      format.json do
        render json: ActivityPub::ActorSerializer.new(@account),
               with_context: true,
               content_type: 'application/activity+json'
      end
    end
  end

  def recent
    @account = find_account
    set_meta_tags @account.decorate
                          .to_meta_tags
                          .merge(title: "Recent stories by #{@account.decorate}")

    stories = StoriesQuery.new.recent
    stories = StoriesQuery.new(stories).for_account(@account)

    @stories = stories.page(params[:page])

    render :index
  end

  private

  def find_account
    Account.local.find_by!(username: params[:username]).decorate
  end
end

app/controllers/api/ujs/stories_controller.rb
class Api::Ujs::StoriesController < Api::Ujs::BaseController
  def toggle_vote
    user_needed
    story = find_story
    authorize story

    outcome = Stories::ToggleVote.run(story: story, account: current_user.account)
    set_account_upvoted_story_ids

    render 'stories/_story', layout: false, locals: { story: outcome.result.voteable }
  end

  def scrap
    story = find_story
    authorize story, :scrap?

    Stories::Rescrap.run(story: story, user: current_user)

    head :no_content
  end

  private

  def find_story
    Story.find(params[:id])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  layout 'application'

  before_action :set_account_upvoted_story_ids

  def index
    @page_title = 'Hot stories'
    @stories = StoriesQuery.new.hot.page(params[:page])
  end

  def recent
    @page_title = 'Recent stories'
    @stories = StoriesQuery.new.recent.page(params[:page])
    render :index
  end

  def show
    set_account_upvoted_comment_ids

    @story = Story.find(params[:id])
    @comments = @story.comments.includes(:account).hash_tree
    @comment = Comments::Create.new(
      story_id: @story.id
    )

    respond_to do |format|
      format.html
      format.json do
        render json: ActivityPub::StorySerializer.new(@story),
               with_context: true,
               content_type: 'application/activity+json'
      end
    end
  end

  def new
    @story = Stories::Create.new
    authorize @story
  end

  def create
    authorize Stories::Create

    outcome = Stories::Create.run(
      title: params.fetch(:story)[:title],
      url: params.fetch(:story)[:url],
      description: params.fetch(:story)[:description],
      tag_list: params.fetch(:story)[:tag_list],
      account: current_account
    )

    if outcome.valid?
      redirect_to outcome.result, notice: 'Story has been created'
    else
      @story = outcome
      render :new
    end
  end

  def edit
    story = find_story
    authorize story

    @story = Stories::Update.new(
      story: story,
      url: story.url,
      title: story.title,
      tag_list: story.tag_names.join(', '),
      description: story.description,
    )
  end

  def update
    story = find_story
    authorize story

    outcome = Stories::Update.run(
      story: story,
      url: params.fetch(:story)[:url],
      title: params.fetch(:story)[:title],
      tag_list: params.fetch(:story)[:tag_list],
      description: params.fetch(:story)[:description],
      account: current_account
    )

    if outcome.valid?
      redirect_to outcome.result, notice: 'Story has been updated'
    else
      @story = outcome
      render :edit
    end
  end

  private

  def find_story
    Story.find(params[:id])
  end
end

app/controllers/tags/stories_controller.rb
class Tags::StoriesController < ApplicationController
  layout 'application'

  before_action :set_account_upvoted_story_ids

  def hot
    @tag = find_tag
    stories = StoriesQuery.new.hot
    stories = StoriesQuery.new(stories).tagged_with([@tag.name])

    @stories = stories.page(params[:page])

    render :index
  end

  def recent
    @tag = find_tag
    stories = StoriesQuery.new.recent
    stories = StoriesQuery.new(stories).tagged_with([@tag.name])

    @stories = stories.page(params[:page])

    render :index
  end

  private

  def find_tag
    Gutentag::Tag.find_by!(name: params[:tag_name]).decorate
  end
end

app/views/stories/_form.html.slim
- url = story.is_a?(Stories::Update) ? story_path(story.story) : stories_path
- method = story.is_a?(Stories::Update) ? :put : :post

= simple_form_for story, as: :story,
                         url: url,
                         wrapper: :spectre_vertical_form,
                         method: method,
                         html: { data: { controller: 'story-form' } } do |f|

  - if f.object.errors[:base].any?
    .toast.toast-error
      h5 = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  / Story URL
  .form-group(class=('has-error' if f.object.errors[:url].any?))
    label.form-label URL
    .input-group
      = f.input_field :url, placeholder: 'https://...',
                            class: 'form-input',
                            data: { target: 'story-form.urlInput', action: 'keyup->story-form#handleUrlChange' },
                            disabled: !policy(f.object).update_url?

      button.btn.btn-primary.input-group-btn(
        data-action="click->story-form#fetchTitle"
        data-target="story-form.fetchTitleBtn"
        disabled=!f.object.url.present?
      )
        | Fetch title

    = f.full_error :url, class: 'form-input-hint'
    div.form-input-hint.text-gray
      | Optional when providing description.

  / Story title
  = f.input :title, input_html: { class: 'input-lg',
                    data: { target: 'story-form.titleInput' } },
                    required: false

  / Story tags
  .form-group.story_tag_list(class=('has-error' if f.object.errors[:tag_list].any?))
    = f.label :tag_list, class: 'form-label'
    input(
      data-target="story-form.tagsPhantomInput"
      data-max-tags=Setting.max_story_tags
      value=f.object.tag_list
    )

    = f.input_field :tag_list, as: :hidden,
                               hint: 'Comma-separated list of tags',
                               data: { target: 'story-form.tagsInput' }

    = f.full_error :tag_list, class: 'form-input-hint'

  / Story description
  = f.input :description, as: :text,
                          hint: 'Optional when submitting a URL. Not for summarizing the post.',
                          input_html: { rows: 5 }

  = f.submit class: 'btn btn-primary'

app/views/stories/_guidelines.html.slim
.column.col-3.story-form-guidelines
  .box
    .box-body.text-sm
      p This community strives for quality content, and bans users very liberally, so behave yourself:
      ul
        li Be nice. Or else.
        li Self-promotion is acceptable, as long as it's not for paid goods.
        li Clickbait titles are not welcome.
        li Titles should be clear and free of extranous components.
        li Links older than a year should have year of their creation parenthesised in the story title.
        li Use description field only for no-url stories or when additional context or explanation for the URL is needed.

app/views/stories/_list.html.slim
ul.list-unstyled.stories-list
  - stories.each do |story|
    = render 'stories/story', story: story

app/views/stories/_story.html.slim
- presenter = StoryPresenter.new(story)
- is_upvoted = @account_upvoted_story_ids.include? story.id
- account = story.account.decorate
- more_actions_available = policy(story).edit? && policy(story).scrap?

li.story-row(data-controller="story" data-voted=is_upvoted.to_s class=('story-row--voted' if is_upvoted))
  .columns
    .column.col-1.story-row-score
      a.story-row-score-btn(
        data-action="click->story#toggleVote"
        data-target="story.voteBtn"
        data-action-path=toggle_vote_api_ujs_story_path(story)
      )
        span.story-row-score-votes-count
          = story.votes_count

    .column.col-2.story-row-thumb
      = link_to story_path(story) do
        - if story.thumb.present?
          = image_tag story.thumb_url(:size_200), width: '100%'
        - else
          .story-row-thumb-empty(class=('story-row-thumb-empty--text' if story.url.blank?))

    .column
      h3.story-row-title
        - if story.url.present?
          = link_to story.title, story.url, target: '_blank'
        - else
          = link_to story.title, story_path(story)

      ul.story-row-meta.list-inline
        - if story.account.present?
          li.list-inline-item
            | @#{link_to story.account.username, account.path}

        li.list-inline-item
          = story.url_domain

        - presenter.primary_tags.each do |tag|
          li.list-inline-item
            | ##{link_to tag.name, tag.path}

        - if presenter.more_tags.any?
          li.list-inline-item
            div.popover.popover-bottom.story-row-tags-more
              a + #{presenter.more_tags.size} more
              .popover-container
                .panel
                  .panel-body
                    ul.list-inline
                      - presenter.more_tags.each do |tag|
                        li.list-inline-item
                          | ##{link_to tag.name, tag.path}

      - if presenter.excerpt.present?
        p.story-row-excerpt
          = presenter.excerpt

      ul.story-row-meta.list-inline
        li.list-inline-item
          = link_to story_path(story) do
            | #{story.comments_count} comments

        li.list-inline-item
          = link_to story_path(story) do
            | Posted
            span.ml-1(data-controller="time-ago" data-datetime=story.created_at.iso8601)
              = story.created_at

        - if user_signed_in? && more_actions_available
          li.list-inline-item •
          li.list-inline-item
            div.dropdown
              a.dropdown-toggle(href="javascript:void(0);" data-turbolinks="false") More

              ul.menu
                - if policy(story).edit?
                  li.menu-item
                    = link_to 'Edit', edit_story_path(story)

                - if policy(story).scrap?
                  li.menu-item
                    a(
                      href="#"
                      data-action="click->story#scrap"
                      data-action-path=scrap_api_ujs_story_path(story)
                    ) Scrap again

app/views/stories/edit.html.slim
.columns
  .column.col-9
    .box
      .box-body.p-4
        h1.h3 Edit story

        .divider
        = render 'stories/form', story: @story

  = render 'stories/guidelines'

app/views/stories/index.html.slim
= render 'shared/popular_tags'

.columns
  .column.col-12
    .box
      .box-nav
        ul.tab
          li.tab-item
            = active_link_to 'Hot', root_path, active: :exclusive
          li.tab-item
            = active_link_to 'Recent', recent_stories_path

      = render 'stories/list', stories: @stories

    = paginate @stories, theme: :mini_box

app/views/stories/new.html.slim
.columns
  .column.col-9
    .box
      .box-body.p-4
        h1.h3 Post a Story
        p Submit a link or provide a description to start a discussion. Check the guidelines to make sure what you're posting is appropriate for the community.

        .divider
        = render 'stories/form', story: @story

  = render 'stories/guidelines'

app/views/stories/show.html.slim
- set_meta_tags @story.decorate

.columns
  .column.col-12
    == StoryPreviewPresenter.new(@story).render

    .stories-list
      ul.list-unstyled
        = render @story

      - if @story.description.present?
        .p-4.px-5.mb-4
          == @story.decorate.description_html

    .box(data-controller="comments-tree")
      / New comment in thread notification template. It's gonna be copied and
      / pasted in appropriate place (child comments) for a comment each time websocket
      / is received
      li.comment-new-reply.d-none(data-target="comments-tree.newReplyToastTpl")
        .toast.toast-warning.toast-sm
          | New reply has been added.
          a.ml-1(href="" data-action="comment#loadNewComment" data-comment-id="")
            | Load it

      .box-body(style="padding: 1.5rem" data-controller="first-comment")
        .root-comment-form
          - if @comments.any?
            = render template: 'comments/new', comment: @comment

          - else
            .empty(data-target="first-comment.empty")
              .empty-icon
                i.icon.icon-people
              p.empty-title.h5 No comments yet
              p.empty-subtitle Click the button to start a conversation.
              .empty-action
                button.btn.btn-primary(
                  data-action="click->first-comment#showForm"
                  data-action-path=new_api_ujs_comment_path(story_id: @story.id)
                )
                  | Add first comment

        ul.comment-children(data-target="comments-tree.rootComments")
          - @comments.each do |comment, children|
            = render 'comments/comment', comment: comment, children: children, show_children: true